events/urls.py
from django.urls import path
from . import views

app_name = 'events'

urlpatterns = [
    path('list/', views.event_list, name='event_list'),
    path('detail/<int:pk>/', views.event_detail, name='event_detail'),
]

realworlddjango/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]
urlpatterns += [
    path('events/', include('events.urls'))
]

urlpatterns += [
    path('api/events/', include('events.urls_api')),
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from django.contrib.auth.models import User
from django.urls import reverse
from django.conf import settings

# Create your models here.


class Category(models.Model):
    title = models.CharField(max_length=90, verbose_name='Категория', default='')

    def display_event_count(self):
        return self.events.count()
    display_event_count.short_description = 'Количество событий для категории'

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Категории'
        verbose_name = 'Категория'


class Feature(models.Model):
    title = models.CharField(max_length=90, verbose_name='Свойство события', default='')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Свойства событий'
        verbose_name = 'Свойство события'


class Event(models.Model):

    EVENT_OCCUPANCY_LHALF = '<= 50%'
    EVENT_OCCUPANCY_GHALF = '> 50%'
    EVENT_OCCUPANCY_SOLDOUT = 'sold-out'

    EVENT_OCCUPANCY_0_QUERY = '0'
    EVENT_OCCUPANCY_1_QUERY = '1'
    EVENT_OCCUPANCY_2_QUERY = '2'

    title = models.CharField(max_length=200, verbose_name='Название', default='')
    description = models.TextField(verbose_name='Описание', default='')
    date_start = models.DateTimeField(verbose_name='Дата начала')
    participants_number = models.PositiveSmallIntegerField(
        verbose_name='Количество участников',
        validators=[MinValueValidator(0), (MaxValueValidator(10000))]
    )
    is_private = models.BooleanField(verbose_name='Частное', default=False)
    category = models.ForeignKey(Category, null=True, on_delete=models.SET_DEFAULT, default='', related_name='events', verbose_name='Категория')
    features = models.ManyToManyField(Feature, verbose_name='Свойства события')
    logo = models.ImageField(upload_to='events/events', blank=True, null=True)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'События'
        verbose_name = 'Событие'

    def get_absolute_url(self):
        return reverse('events:event_detail', args=[str(self.pk)])

    @property
    def rate(self):
        event_reviews_list = self.reviews.all()
        if event_reviews_list.count() == 0:
            rate_result = 0
        else:
            rate_sum = 0
            for review in event_reviews_list:
                rate_sum += review.rate
            rate_result = round(rate_sum / event_reviews_list.count(), 1)
        return rate_result

    @property
    def logo_url(self):
        return self.logo.url if self.logo else f'{settings.STATIC_URL}images/svg-icon/event.svg'

    def display_enroll_count(self):
        return self.enrolls.count()
    display_enroll_count.short_description = 'Количество записей'

    def places_left(self):
        return self.participants_number - self.enrolls.count()
    places_left_prop = property(places_left)

    def occupancy_estimation(self):
        return self.places_left_prop / self.participants_number
    occupancy_estimation_prop = property(occupancy_estimation)

    def estimate_places_left(self):
        value = ''
        if self.occupancy_estimation_prop >= 0.5:
            value = self.EVENT_OCCUPANCY_0_QUERY
        elif self.occupancy_estimation_prop < 0.5 and self.places_left_prop != 0:
            value = self.EVENT_OCCUPANCY_1_QUERY
        elif self.places_left_prop == 0:
            value = self.EVENT_OCCUPANCY_2_QUERY
        return value
    estimate_places_left_prop = property(estimate_places_left)

    def display_places_left(self):
        occupancy = ''
        if self.estimate_places_left_prop == '1':
            occupancy = self.EVENT_OCCUPANCY_GHALF
        elif self.estimate_places_left_prop == '0':
            occupancy = self.EVENT_OCCUPANCY_LHALF
        elif self.estimate_places_left_prop == '2':
            occupancy = self.EVENT_OCCUPANCY_SOLDOUT
        return f'{self.places_left_prop} ({occupancy})'
    display_places_left.short_description = 'Осталось мест'


class Enroll(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_DEFAULT, default='', related_name='enrolls', verbose_name='Пользователь')
    event = models.ForeignKey(Event, null=True, on_delete=models.SET_DEFAULT, default='', related_name='enrolls', verbose_name='Событие')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')

    class Meta:
        verbose_name_plural = 'Записи на события'
        verbose_name = 'Запись на событие'


class Review(models.Model):
    user = models.ForeignKey(User, null=True, on_delete=models.SET_DEFAULT, default='', related_name='reviews', verbose_name='Пользователь')
    event = models.ForeignKey(Event, null=True, on_delete=models.SET_DEFAULT, default='', related_name='reviews', verbose_name='Событие')
    rate = models.PositiveSmallIntegerField(null=True, default='', verbose_name='Оценка пользователя')
    text = models.TextField(null=True, default='', blank=True, verbose_name='Текст отзыва')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')

    class Meta:
        verbose_name_plural = 'Отзывы'
        verbose_name = 'Отзыв'

    def __str__(self):
        return f'{self.user} - {self.rate} - {self.event}'

events/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse
from events.models import Event, Review
from django.contrib.auth.models import User
from django.views.decorators.http import require_POST
from django.http import HttpResponse
from datetime import datetime


# Create your views here.


def event_list(request):
    template_name = 'events/event_list.html'
    event_objects = Event.objects.all()
    context = {
        'event_objects': event_objects,
    }
    return render(request, template_name, context)


def event_detail(request, pk):
    template_name = 'events/event_detail.html'
    event = get_object_or_404(Event, pk=pk)
    review_objects = event.reviews.all()
    context = {
        'event': event,
        'rate': event.rate,
        'review_objects': review_objects,
    }
    return render(request, template_name, context)


@require_POST
def create_review(request):
    rate = ''
    text = ''
    user_name = ''
    formatted_date = ''

    if request.user and request.user.is_authenticated:

        event_id = request.POST.get('event_id')
        rate = request.POST.get('rate')
        text = request.POST.get('text')
        msg = ''
        event = get_object_or_404(Event, pk=event_id)
        user_id = get_object_or_404(User, pk=request.user.id)
        user_name = request.user.username
        date = datetime.now()
        formatted_date = date.strftime('%d.%m.%Y')
        review_already_created = False

        user_id_list = []
        for review in event.reviews.all():
            user_id_list.append(review.user.id)
        if user_id.id in user_id_list:
            review_already_created = True

        new_review = Review(user=user_id,
                            event=event,
                            rate=rate,
                            text=text,
                            created=formatted_date,
                            updated=formatted_date
                            )

        if review_already_created:
            validity = False
            msg = 'Вы уже оставляли отзыв к этому событию'
        elif rate == '' or text == '':
            validity = False
            msg = 'Оценка и текст отзыва - обязательные поля'
        else:
            validity = True
            new_review.save()
    else:
        validity = False
        msg = 'Отзывы могут оставлять только зарегистрированные пользователи'

    data = {
        'ok': validity, # True если отзыв создан успешно, False в противном случае,
        'msg': msg,  # Сообщение об ошибке
        'rate': rate,  # Оценка отзыва
        'text': text,  # Текст отзыва
        'created': formatted_date,  # Дата создания отзыва в формате DD.MM.YYYY
        'user_name': user_name,  # Полное имя пользователя
    }

    return JsonResponse(data)

events/templates/events/event_list.html
{% extends "__base.html" %}
{% load static %}
{% block title %}Real World Django - События{% endblock %}
{% load eventstags %}

{% block content %}

	<div class="vertical-layout">

		{% include "snippets/_left_menu.html" %}

	    <!-- Start MAIN_CONTAINER -->
	    <div class="rightbar">

		    {% with "События" as header %}
			    {% include "snippets/_top_bar.html" %}
		    {% endwith %}



	        <!-- Start CONTAINER_BAR -->
	        <div class="container-fluid mt-3">
	            <div class="row mb-4">
	                <div class="col">
	                    <div class="card shadow">
	                        <div class="card-body">
	                            <form>
	                                <div class="row row-cols-lg-auto g-3 align-items-start">
	                                    <div class="col-12">
	                                        <label for="category" class="form-label">Категория:</label>
	                                        <select class="form-select" id="category">
	                                            <option selected="">....................</option>
	                                            <option value="1">Спортивный турнир</option>
	                                            <option value="2">Семейное мероприятие</option>
	                                            <option value="3">Субботник</option>
	                                            <option value="4">Волонтерство</option>
	                                            <option value="5">Night Party</option>
	                                            <option value="6">Дилоги со звездой</option>
	                                        </select>
	                                    </div>
	                                    <div class="col-12">
	                                        <label for="features" class="form-label">Свойства:</label>
	                                        <select class="form-select" multiple="" id="features">
	                                            <option value="1">На открытом воздухе</option>
	                                            <option value="2">Приглашенная знаменитость</option>
	                                            <option value="3">Живая музыка</option>
	                                            <option value="4">Песни у костра</option>
	                                            <option value="5">Подарки участникам</option>
	                                            <option value="6"> Вечерние танцы</option>
	                                        </select>
	                                    </div>
	                                    <div class="col-12 d-md-flex">
	                                        <div class="mx-1">
	                                            <label for="id_date_start" class="form-label">Дата начала</label>
	                                            <input type="date" class="form-control" id="id_date_start">
	                                        </div>
	                                        <div class="mx-1">
	                                            <label for="id_date_end" class="form-label">Дата окончания</label>
	                                            <input type="date" class="form-control" id="id_date_end">
	                                        </div>
	                                    </div>
	                                </div>
	                                <div class="row mt-3">
	                                    <div class="col-12 d-md-flex">
	                                        <div class="form-check me-3">
	                                            <input class="form-check-input" type="checkbox" value="" id="is_private">
	                                            <label class="form-check-label" for="is_private">
	                                                Private
	                                            </label>
	                                        </div>
	                                        <div class="form-check">
	                                            <input class="form-check-input" type="checkbox" value="" id="is_available">
	                                            <label class="form-check-label" for="is_available">
	                                                Есть места
	                                            </label>
	                                        </div>
	                                    </div>
	                                    <div class="col-12 mt-3">
	                                        <button type="submit" class="btn btn-primary">Фильтровать</button>
	                                        <button type="submit" class="btn btn-outline-danger">Сбросить</button>
	                                    </div>
	                                </div>
	                            </form>
	                        </div>
	                    </div>
	                </div>
	            </div>
	            <ul class="pagination">
	                <li class="page-item"><a class="page-link" href="#" data-test="p_start">&laquo;</a></li>
	                <li class="page-item"><a class="page-link" href="#" data-test="p_previous">Previous</a></li>
	                <li class="page-item"><a class="page-link" href="#" data-test="p_1">1</a></li>
	                <li class="page-item active"><a class="page-link" href="#" data-test="p_2">2</a></li>
	                <li class="page-item"><a class="page-link" href="#" data-test="p_3">3</a></li>
	                <li class="page-item"><a class="page-link" href="#" data-test="p_next">Next</a></li>
	                <li class="page-item"><a class="page-link" href="#" data-test="p_end">&raquo;</a></li>
	            </ul>
	            <div class="row row-cols-1 row-cols-md-2 row-cols-xl-3 row-cols-xxl-4 g-4">
		            {% for event in event_objects %}
	                <div class="col">
	                    <div class="card h-100">
	                        <div class="card-header">
	                            <h5 class="card-title mb-0">{{ event.title }}</h5>
		                        {% if event.is_private == True %}
	                                <span data-test="is_private" class="badge bg-dark">
		                                Private
	                                </span>
		                        {% endif %}
	                        </div>
	                        <div class="card-body">
	                            <h3>{{ event.display_enroll_count }} из {{ event.participants_number }}</h3>
	                            <p>участников</p>
	                            <ul class="py-2">
		                            {% include "snippets/_event_features.html" %}
	                            </ul>
	                            <p>
	                                дата: <strong data-test="date_start">{{ event.date_start|eventsdate }}</strong>
	                            </p>
	                        </div>
	                        <div class="card-footer">
	                            <a href="{{ event.get_absolute_url }}" class="btn btn-success">Смотреть</a>
	                            <a href="#" class="btn btn-outline-primary" title="Изменить">
	                                <i class="bi bi-pencil-square"></i>Изменить
	                            </a>
	                        </div>
	                    </div>
	                </div>
		            {% endfor %}
	            </div>
	        </div>
	        <!-- End CONTAINER_BAR -->

			{% include "snippets/_footer.html" %}

	    </div>
	    <!-- End MAIN_CONTAINER -->

	</div>

{% endblock %}

events/templates/events/event_list_semple.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <title>Real World Django - События</title>
    <!-- Bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <!-- Bootstrap Icons -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <!-- Project style -->
    <link href="assets/css/style.css" rel="stylesheet" type="text/css">
</head>
<body>

<div class="vertical-layout">

    <!-- Start LEFT_MENU -->
    <div class="leftbar">
        <div class="logobar">
            <a href="index.html" class="logo logo-large">
                <img src="assets/images/svg-icon/logo.svg" alt="logo" style="height: 40px">
            </a>
        </div>
        <ul class="vertical-menu" id="vertical-menu">
            <li class="vertical-menu-item">
                <span>Главное</span>
                <ul class="vertical-submenu">
                    <li><a href="event_list.html">События</a></li>
                    <li><a href="mail.html">Подписчики</a></li>
                </ul>
            </li>
            <li class="vertical-menu-item">
                <span>Аккаунт</span>
                <ul class="vertical-submenu">
                    <li><a href="profile.html">Мой аккаунт</a></li>
                    <li><a href="#">Изменить пароль</a></li>
                    <li><a href="#">Сбросить пароль</a></li>
                </ul>
            </li>
        </ul>
    </div>
    <!-- menu for mobile -->
    <div class="topbar-mobile">
        <div class="row align-items-center">
            <div class="col-md-12">
                <div class="mobile-logobar" style="max-width: 40px">
                    <a href="#" class="mobile-logo">
                        <img src="assets/images/svg-icon/logo.svg" class="img-fluid" alt="logo">
                    </a>
                </div>
                <div class="mobile-togglebar">
                    <ul class="list-inline mb-0">
                        <li class="list-inline-item">
                            <div class="menubar">
                                <a class="menu-hamburger" href="#" id="menu-hamburger">
                                    <img src="assets/images/svg-icon/collapse.svg"
                                         class="img-fluid menu-hamburger-collapse"
                                         alt="collapse">
                                    <img src="assets/images/svg-icon/close.svg"
                                         class="img-fluid menu-hamburger-close"
                                         alt="close">
                                </a>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="d-md-none" style="height: 90px"></div>
    <!-- End LEFT_MENU -->

    <!-- Start MAIN_CONTAINER -->
    <div class="rightbar">

        <!-- Start TOP_BAR -->
        <div class="container-fluid bg-white py-3">
            <div class="row align-items-center justify-content-between">
                <div class="col-auto text-center ms-4">
                    <h4>События</h4>
                </div>
                <div class="col-auto text-center me-4">
                    <a href="#" class="btn btn-outline-primary">+ Добавить событие</a>
                </div>
            </div>
        </div>
        <!-- End TOP_BAR -->

        <!-- Start CONTAINER_BAR -->
        <div class="container-fluid mt-3">
            <div class="row mb-4">
                <div class="col">
                    <div class="card shadow">
                        <div class="card-body">
                            <form>
                                <div class="row row-cols-lg-auto g-3 align-items-start">
                                    <div class="col-12">
                                        <label for="category" class="form-label">Категория:</label>
                                        <select class="form-select" id="category">
                                            <option selected="">....................</option>
                                            <option value="1">Спортивный турнир</option>
                                            <option value="2">Семейное мероприятие</option>
                                            <option value="3">Субботник</option>
                                            <option value="4">Волонтерство</option>
                                            <option value="5">Night Party</option>
                                            <option value="6">Дилоги со звездой</option>
                                        </select>
                                    </div>
                                    <div class="col-12">
                                        <label for="features" class="form-label">Свойства:</label>
                                        <select class="form-select" multiple="" id="features">
                                            <option value="1">На открытом воздухе</option>
                                            <option value="2">Приглашенная знаменитость</option>
                                            <option value="3">Живая музыка</option>
                                            <option value="4">Песни у костра</option>
                                            <option value="5">Подарки участникам</option>
                                            <option value="6"> Вечерние танцы</option>
                                        </select>
                                    </div>
                                    <div class="col-12 d-md-flex">
                                        <div class="mx-1">
                                            <label for="id_date_start" class="form-label">Дата начала</label>
                                            <input type="date" class="form-control" id="id_date_start">
                                        </div>
                                        <div class="mx-1">
                                            <label for="id_date_end" class="form-label">Дата окончания</label>
                                            <input type="date" class="form-control" id="id_date_end">
                                        </div>
                                    </div>
                                </div>
                                <div class="row mt-3">
                                    <div class="col-12 d-md-flex">
                                        <div class="form-check me-3">
                                            <input class="form-check-input" type="checkbox" value="" id="is_private">
                                            <label class="form-check-label" for="is_private">
                                                Private
                                            </label>
                                        </div>
                                        <div class="form-check">
                                            <input class="form-check-input" type="checkbox" value="" id="is_available">
                                            <label class="form-check-label" for="is_available">
                                                Есть места
                                            </label>
                                        </div>
                                    </div>
                                    <div class="col-12 mt-3">
                                        <button type="submit" class="btn btn-primary">Фильтровать</button>
                                        <button type="submit" class="btn btn-outline-danger">Сбросить</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <ul class="pagination">
                <li class="page-item"><a class="page-link" href="#" data-test="p_start">&laquo;</a></li>
                <li class="page-item"><a class="page-link" href="#" data-test="p_previous">Previous</a></li>
                <li class="page-item"><a class="page-link" href="#" data-test="p_1">1</a></li>
                <li class="page-item active"><a class="page-link" href="#" data-test="p_2">2</a></li>
                <li class="page-item"><a class="page-link" href="#" data-test="p_3">3</a></li>
                <li class="page-item"><a class="page-link" href="#" data-test="p_next">Next</a></li>
                <li class="page-item"><a class="page-link" href="#" data-test="p_end">&raquo;</a></li>
            </ul>
            <div class="row row-cols-1 row-cols-md-2 row-cols-xl-3 row-cols-xxl-4 g-4">
                <div class="col">
                    <div class="card h-100">
                        <div class="card-header">
                            <h5 class="card-title mb-0">Вечерний субботник во вторник</h5>
                            <span data-test="is_private" class="badge bg-dark">Private</span>
                        </div>
                        <div class="card-body">
                            <h3>12 из 100</h3>
                            <p>участников</p>
                            <ul class="py-2">
                                <li>Музыка</li>
                                <li>На открытом воздухе</li>
                                <li>Приглашенные звезды</li>
                            </ul>
                            <p>
                                дата: <strong data-test="date_start">01.01.2001 в 23:59</strong>
                            </p>
                        </div>
                        <div class="card-footer">
                            <a href="event_detail.html" class="btn btn-success">Смотреть</a>
                            <a href="event_update.html" class="btn btn-outline-primary" title="Изменить">
                                <i class="bi bi-pencil-square"></i>Изменить
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card h-100">
                        <div class="card-header">
                            <h5 class="card-title mb-0">VR Рисование в Виртуальной реальности</h5>
                            <p class="mb-0"><span class="badge bg-dark">Private</span></p>
                        </div>
                        <div class="card-body">
                            <h3>12 из 100</h3>
                            <p>участников</p>
                            <ul class="py-2">
                                <li>Музыка</li>
                                <li>На открытом воздухе</li>
                                <li>Приглашенные звезды</li>
                            </ul>
                            <p class="text-black">дата: <strong>27.12.2021 в 12:00</strong></p>
                        </div>
                        <div class="card-footer">
                            <a href="event_detail.html" class="btn btn-success">Смотреть</a>
                            <a href="event_update.html" class="btn btn-outline-primary" title="Редактировать">
                                <i class="bi bi-pencil-square"></i>Изменить
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card h-100">
                        <div class="card-header">
                            <h5 class="card-title mb-0">Шоу «Big Stand Up»</h5>
                        </div>
                        <div class="card-body">
                            <h3>12 из 100</h3>
                            <p>участников</p>
                            <ul class="py-2">
                                <li>Музыка</li>
                                <li>На открытом воздухе</li>
                                <li>Приглашенные звезды</li>
                            </ul>
                            <p class="text-black">дата: <strong>27.12.2021 в 12:00</strong></p>
                        </div>
                        <div class="card-footer">
                            <a href="event_detail.html" class="btn btn-success">Смотреть</a>
                            <a href="event_update.html" class="btn btn-outline-primary" title="Редактировать">
                                <i class="bi bi-pencil-square"></i>Изменить
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- End CONTAINER_BAR -->

        <!-- Start FOOTER -->
        <div style="height: 70px"></div>
        <div class="footerbar">
            <footer class="footer">
                <p class="mb-0">© Pumpskill. Real World Django</p>
            </footer>
        </div>
        <!-- End FOOTER -->

    </div>
    <!-- End MAIN_CONTAINER -->

</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>
<script src="assets/js/main.js"></script>
</body>
</html>